version: 2
updates:
- package-ecosystem: bundler
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: nokogiri
    versions:
    - 1.11.1
    - 1.11.2
  - dependency-name: excon
    versions:
    - 0.78.1
    - 0.79.0
  - dependency-name: ffi
    versions:
    - 1.14.2
  - dependency-name: middleman-livereload
    versions:
    - 3.4.6
